/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	inferencerv1 "kube-inferencer/pkg/apis/inferencer/v1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeInferencers implements InferencerInterface
type FakeInferencers struct {
	Fake *FakeInferencerV1
	ns   string
}

var inferencersResource = schema.GroupVersionResource{Group: "inferencer.k8s.io", Version: "v1", Resource: "inferencers"}

var inferencersKind = schema.GroupVersionKind{Group: "inferencer.k8s.io", Version: "v1", Kind: "Inferencer"}

// Get takes name of the inferencer, and returns the corresponding inferencer object, and an error if there is any.
func (c *FakeInferencers) Get(ctx context.Context, name string, options v1.GetOptions) (result *inferencerv1.Inferencer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(inferencersResource, c.ns, name), &inferencerv1.Inferencer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*inferencerv1.Inferencer), err
}

// List takes label and field selectors, and returns the list of Inferencers that match those selectors.
func (c *FakeInferencers) List(ctx context.Context, opts v1.ListOptions) (result *inferencerv1.InferencerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(inferencersResource, inferencersKind, c.ns, opts), &inferencerv1.InferencerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &inferencerv1.InferencerList{ListMeta: obj.(*inferencerv1.InferencerList).ListMeta}
	for _, item := range obj.(*inferencerv1.InferencerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested inferencers.
func (c *FakeInferencers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(inferencersResource, c.ns, opts))

}

// Create takes the representation of a inferencer and creates it.  Returns the server's representation of the inferencer, and an error, if there is any.
func (c *FakeInferencers) Create(ctx context.Context, inferencer *inferencerv1.Inferencer, opts v1.CreateOptions) (result *inferencerv1.Inferencer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(inferencersResource, c.ns, inferencer), &inferencerv1.Inferencer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*inferencerv1.Inferencer), err
}

// Update takes the representation of a inferencer and updates it. Returns the server's representation of the inferencer, and an error, if there is any.
func (c *FakeInferencers) Update(ctx context.Context, inferencer *inferencerv1.Inferencer, opts v1.UpdateOptions) (result *inferencerv1.Inferencer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(inferencersResource, c.ns, inferencer), &inferencerv1.Inferencer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*inferencerv1.Inferencer), err
}

// Delete takes name of the inferencer and deletes it. Returns an error if one occurs.
func (c *FakeInferencers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(inferencersResource, c.ns, name), &inferencerv1.Inferencer{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeInferencers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(inferencersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &inferencerv1.InferencerList{})
	return err
}

// Patch applies the patch and returns the patched inferencer.
func (c *FakeInferencers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *inferencerv1.Inferencer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(inferencersResource, c.ns, name, pt, data, subresources...), &inferencerv1.Inferencer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*inferencerv1.Inferencer), err
}
